---
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y curl

install:
  # Install Ansible.
  - pip install ansible

script:
  # Copy example files into place.
  - cp example.config.yml config.yml
  - cp example.drupal.make.yml drupal.make.yml

  # Check the role/playbook's syntax.
  - 'ansible-playbook -i "localhost," -c local provisioning/playbook.yml --syntax-check'

  # Check the config file and drupal make file YAML syntax.
  - >
    python -c "import yaml; yaml.load( open('example.config.yml', 'r'), Loader=yaml.CLoader  )"
  - >
    python -c "import yaml; yaml.load( open('example.drupal.make.yml', 'r'), Loader=yaml.CLoader  )"

  # Make sure Ansible requirements install correctly.
  - 'ansible-galaxy install -r requirements.txt'
