version: "3"

services:

  drupal-vm:
    # Switch the image to `geerlingguy/drupal-vm` if not using your own image.
    image: drupal-vm
    container_name: drupal-vm
    ports:
      - 80:80
      - 443:443
    privileged: true
    # Use of the `cached` option requires the Docker Edge release as of May '17.
    volumes:
      - ./:/var/www/drupalvm/:rw,cached
    command: /lib/systemd/systemd
    networks:
      drupalvm:
        ipv4_address: 192.168.88.88

networks:

  drupalvm:
    driver: bridge
    driver_opts:
      ip: 192.168.88.1
    ipam:
      config:
        - subnet: "192.168.88.0/16"
