---
# Originally I tried adding to the www group, but because Ansible uses one SSH
# connection, that broke the initial provisioning, since groups aren't refreshed
# without a new session or log off/log on.
- name: Ensure admin group exists.
  group: name=admin state=present

- name: Ensure vagrant user is in admin group.
  user: name=vagrant append=yes groups=admin

- name: Set permissions on /var/www.
  file: >
    path=/var/www
    state=directory
    owner=vagrant
    group=admin
    mode=775
    recurse=yes

- name: Remove 000-default.conf file.
  file: >
    path=/etc/apache2/sites-enabled/000-default.conf
    state=absent
  notify: restart webserver
