site_name: Drupal VM

repo_url: https://github.com/geerlingguy/drupal-vm
site_description: 'Drupal VM - A VM for local Drupal development, built with Vagrant + Ansible'
theme: readthedocs

markdown_extensions:
    - toc:
        permalink: True

pages:
- ['index.md', 'Home']
